let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Viajante Solitário",
    price: 8,
    desc: "Jack Kerouac",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Tristessa",
    price: 8,
    desc: "Jack Kerouac",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "A queda da América",
    price: 8,
    desc: "Allen Ginsberg",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Junky",
    price: 10,
    desc: "William Burroughs",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Queer",
    price: 10,
    desc: "William Burroughs",
    img: "images/img-5.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Almoço Nu",
    price: 10,
    desc: "William Burroughs",
    img: "images/img-6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Um parque de diversões na cabeça",
    price: 8,
    desc: "Lawrence Ferlinghetti",
    img: "images/img-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Big Sur",
    price: 8,
    desc: "Jack Kerouac",
    img: "images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "O livro de Jack: uma biografia de Jack Kerouac",
    price: 25,
    desc: "Lawrence Lee",
    img: "images/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Memórias de uma Beatnik",
    price: 25,
    desc: "Diane di Prima",
    img: "images/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Mente Espontânea: entrevistas 1958-1996",
    price: 30,
    desc: "Barry Miles",
    img: "images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Uivo e outros poemas",
    price: 8,
    desc: "Allen Ginsberg",
    img: "images/img-12.png",
  },
];
